### ISSUE TITLE
[Question] Why my expression can't match

### ISSUE THREAD

**Issue by SettingDust** [a-sit-plus/jsonpath4k#20]
It successes in IDEA's json path evaluator

Working:
- `$[?$.tag.id == 'ic2:geo_generator' || $.tag.id == 'ic2:generator']`
- `$[?($.tag.id == 'ic2:geo_generator' || $.tag.id == 'ic2:generator')]`
- `$.tag[?($.tag.id == 'ic2:geo_generator' || $.tag.id == 'ic2:generator')]`

Not working:
- `$.tag.id[?($.tag.id == 'ic2:geo_generator' || $.tag.id == 'ic2:generator')]`
- `$[?(@.tag.id == 'ic2:geo_generator' || @.tag.id == 'ic2:generator')]`
-  `$.tag[?(@.id == 'ic2:geo_generator' || @.id == 'ic2:generator')]`

```json
{
 "id": "ic2:te",
 "meta": 1,
 "pos": {
  "x": 23,
  "y": 64,
  "z": 179
 },
 "dimension": 0,
 "tag": {
  "components": {
   "energy": {
    "storage": 0.0
   }
  },
  "fuel": 0,
  "InvSlots": {
   "charge": {
    "Contents": []
   },
   "fuel": {
    "Contents": []
   }
  },
  "x": 23,
  "y": 64,
  "facing": 2,
  "active": 0,
  "z": 179,
  "id": "ic2:generator",
  "totalFuel": 0
 }
}
```

**Comment by SettingDust** [comment]
TONGYI Lingma told me the expression is matching array XD

**Comment by SettingDust** [comment]
Seems not

**Comment by acrusage-iaik** [comment]
Hello, 

As I can see so far, the paths compile just fine, so I assume the issue is with the result of the queries?
Which results would you expect for the queries listed in your issue?

As for my understanding, the queries should give the following results:
- `$.tag.id[?($.tag.id == 'ic2:geo_generator' || $.tag.id == 'ic2:generator')]` - should return an empty list, as $.tag.id does not have any children, and the filter selector is designed to select all children satisfying the logical expression within. 
- `$[?(@.tag.id == 'ic2:geo_generator' || @.tag.id == 'ic2:generator')]` - should return an empty list - @ in this case would be a child of $ - try it with `@.id` instead.
- `$.tag[?(@.id == 'ic2:geo_generator' || @.id == 'ic2:generator')]` - should return an empty list

**Comment by SettingDust** [comment]
I'm new to json path. I thought the `@` is current node instead of the children. MF

**Comment by acrusage-iaik** [comment]
Don't worry, json path filters are a little complicated, you'll get into it!

It also seems like different tools implement json path filters a little differently for some reason, which makes that journey a little more tedious. Maybe take different tools and compare their outputs. One alternative suggestion to IntelliJ would be https://codebeautify.org/jsonpath-tester#
